"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BadgeCheck, Bell, ChevronsUpDown, CreditCard, LogOut, Sparkles, } from "lucide-react";
import { Avatar, DropdownMenu } from "@/components/base";
import { SidebarMenu, SidebarMenuButton, SidebarMenuItem, useSidebar, } from "./sidebar";
export function NavUser({ user, }) {
    const { isMobile } = useSidebar();
    return (_jsx(SidebarMenu, { children: _jsx(SidebarMenuItem, { children: _jsxs(DropdownMenu.Root, { children: [_jsx(DropdownMenu.Trigger, { children: _jsxs(SidebarMenuButton, { size: "lg", className: "data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground", children: [_jsx(Avatar, { size: "1", name: "CN" }), _jsxs("div", { className: "grid flex-1 text-left text-sm leading-tight", children: [_jsx("span", { className: "truncate font-semibold", children: user.name }), _jsx("span", { className: "truncate text-xs", children: user.email })] }), _jsx(ChevronsUpDown, { className: "ml-auto size-4" })] }) }), _jsxs(DropdownMenu.Content, { className: "w-[--radix-dropdown-menu-trigger-width] min-w-56 rounded-lg", side: isMobile ? "bottom" : "right", align: "end", sideOffset: 4, children: [_jsx(DropdownMenu.Label, { className: "p-0 font-normal", children: _jsxs("div", { className: "flex items-center gap-2 px-1 py-1.5 text-left text-sm", children: [_jsx(Avatar, { size: "1", name: "CN" }), _jsxs("div", { className: "grid flex-1 text-left text-sm leading-tight", children: [_jsx("span", { className: "truncate font-semibold", children: user.name }), _jsx("span", { className: "truncate text-xs", children: user.email })] })] }) }), _jsx(DropdownMenu.Separator, {}), _jsx(DropdownMenu.Group, { children: _jsxs(DropdownMenu.Item, { children: [_jsx(Sparkles, {}), "Upgrade to Pro"] }) }), _jsx(DropdownMenu.Separator, {}), _jsxs(DropdownMenu.Group, { children: [_jsxs(DropdownMenu.Item, { children: [_jsx(BadgeCheck, {}), "Account"] }), _jsxs(DropdownMenu.Item, { children: [_jsx(CreditCard, {}), "Billing"] }), _jsxs(DropdownMenu.Item, { children: [_jsx(Bell, {}), "Notifications"] })] }), _jsx(DropdownMenu.Separator, {}), _jsxs(DropdownMenu.Item, { children: [_jsx(LogOut, {}), "Log out"] })] })] }) }) }));
}
//# sourceMappingURL=nav-user.js.map