import { ProjectsImages } from "./images"
import type { Member, Project } from "./types"

export const members: Member[] = [
  {
    id: "1",
    name: "Shane Black",
    avatar: ProjectsImages?.user,
    color: "bg-blue-500",
  },
  {
    id: "2",
    name: "John Doe",
    avatar: ProjectsImages?.user1,
    color: "bg-red-500",
  },
  {
    id: "3",
    name: "Jane Smith",
    avatar: ProjectsImages?.user2,
    color: "bg-green-500",
  },
  {
    id: "4",
    name: "Emily Johnson",
    avatar: ProjectsImages?.user3,
    color: "bg-purple-500",
  },
  {
    id: "5",
    name: "Michael Brown",
    avatar: ProjectsImages?.user4,
    color: "bg-yellow-500",
  },
]

export const projects: Project[] = [
  {
    id: "1",
    title: "App Development",
    company: "Dropbox, Inc.",
    logo: ProjectsImages?.dropbox,
    description: "Create a mobile application on iOS and Android devices.",
    progress: 50,
    timeLeft: "1",
    timeType: "week",
    members: [members[0], members[1], members[2]],
    status: "started",
  },
  {
    id: "2",
    title: "Website Redesign",
    company: "GitLab Inc.",
    logo: ProjectsImages?.gitlab,
    description:
      "It is necessary to develop a website redesign in a corporate style.",
    progress: 75,
    timeLeft: "1",
    timeType: "week",
    members: [members[1], members[3], members[4]],
    status: "started",
  },
  {
    id: "3",
    title: "Landing Page",
    company: "Bitbucket, Inc.",
    logo: ProjectsImages?.bitbucket,
    description:
      "It is necessary to create a landing together with the development of design.",
    progress: 100,
    timeLeft: "1",
    timeType: "week",
    members: [members[0], members[4]],
    status: "completed",
  },
  {
    id: "4",
    title: "Parser Development",
    company: "Driveway, Inc.",
    logo: ProjectsImages?.python,
    description: "It is necessary to develop a ticket site parser in python.",
    progress: 50,
    timeLeft: "5",
    timeType: "days",
    members: [members[2], members[3], members[4]],
    status: "started",
  },
  {
    id: "5",
    title: "App Development",
    company: "Slack Technologies, Inc.",
    logo: ProjectsImages?.slack,
    description: "Create a mobile application on iOS and Android devices.",
    progress: 50,
    timeLeft: "5",
    timeType: "days",
    members: [members[1], members[4]],
    status: "on-hold",
  },
  {
    id: "6",
    title: "App Development",
    company: "Google, Inc.",
    logo: ProjectsImages?.firebase,
    description: "Create a mobile application on iOS and Android devices.",
    progress: 25,
    timeLeft: "1",
    timeType: "week",
    members: [members[1], members[3]],
    status: "on-hold",
  },
  {
    id: "7",
    title: "Admin Dashboard",
    company: "ArtTemplate, Inc.",
    logo: ProjectsImages?.angular,
    description: "Necessary to create Admin Dashboard on Angular 8.",
    progress: 30,
    timeLeft: "2",
    timeType: "week",
    members: [members[0], members[2]],
    status: "started",
  },
  {
    id: "8",
    title: "Web App on Vue.js",
    company: "ArtTemplate, Inc.",
    logo: ProjectsImages?.vue,
    description: "It is necessary to develop a web app on the framework Vue.js",
    progress: 100,
    timeLeft: "1",
    timeType: "week",
    members: [members[1], members[3], members[4]],
    status: "completed",
  },
  {
    id: "9",
    title: "App Development",
    company: "Facebook, Inc.",
    logo: ProjectsImages?.facebook,
    description: "Create a mobile application on iOS and Android devices.",
    progress: 50,
    timeLeft: "1",
    timeType: "week",
    members: [members[0], members[2]],
    status: "on-hold",
  },
]
