packages:
  - apps/*
  - frontend/*
  - shared/*


catalog:
  lucide-react: 0.471.1
  react: 18.3.1
  react-dom: 18.3.1
  vite: 6.0.7
  vite-tsconfig-paths: 5.1.4
  postcss: 8.5.1
  typescript: 5.7.3
  tailwindcss: 3.4.14
  zod: 3.24.1
  "@radix-ui/themes": 3.1.6
  "@tanstack/react-query": 5.59.16
  "@tanstack/react-router": 1.76.1
  "@types/react": 18.3.1
  "@types/react-dom": 18.3.1
  "@vitejs/plugin-react": 4.3.4
  "@electric-sql/pglite-react": 0.2.15
  "@incmix/utils": 0.1.0

