packages:
  - apps/*
  - frontend/*
  - shared/*


catalog:
  eslint: 9.21.0
  eslint-plugin-react-hooks: 5.1.0
  eslint-plugin-react-refresh: 0.4.19
  globals: 16.0.0
  i18next: 24.2.3
  i18next-chained-backend: 4.6.2
  i18next-http-backend: 3.0.2
  i18next-resources-to-backend: 1.2.1
  immer: 10.1.1
  jsdom: 26.0.0
  json-schema-to-zod: 2.6.1
  lucide-react: 0.474.0
  motion: 12.7.3
  nanoid: 5.1.5
  nuqs: 2.4.1
  postcss: 8.5.3
  react: 19.1.0
  react-dom: 19.1.0
  react-error-boundary: 5.0.0
  react-hook-form: 7.55.0
  react-i18next: 15.4.1
  react-router-dom: 7.5.0
  rollup-plugin-visualizer: 5.14.0
  rxdb: 16.9.0
  rxdb-hooks: 5.0.2
  rxdb-premium: 16.8.1
  sonner: 2.0.3
  swapy: 1.0.5
  tailwindcss: 3.4.14
  tailwindcss-animate: 1.0.7
  tailwind-merge: 3.1.0
  tw-animate-css: 1.2.5
  typescript: 5.8.2
  typescript-eslint: 8.24.1
  vite: 6.2.4
  vitest: 3.1.1
  vite-tsconfig-paths: 5.1.4
  vite-plugin-bundlesize: 0.1.0
  vitest": 3.1.1
  zod: 3.24.2
  zustand: 5.0.3
  "@casl/react": 5.0.0
  "@conform-to/react": 1.4.0
  "@conform-to/zod": 1.4.0
  "@eslint/js": 9.21.0
  "@incmix/utils": 0.3.4
  "@radix-ui/themes": 3.2.1
  "@tailwindcss/typography": 0.5.16
  "@tailwindcss/vite": 4.0.17
  "@tanstack/zod-form-adapter": 0.42.1
  "@tanstack/react-form": 1.4.0
  "@tanstack/react-query": 5.74.3
  "@tanstack/react-router": 1.116.0
  "@tanstack/react-table": 8.21.3
  "@tanstack/router-cli": 1.116.0
  "@tanstack/router-devtools": 1.116.0
  "@tiptap/react": 2.11.5
  "@tiptap/starter-kit": 2.11.5
  "@types/node": 22.14.1
  "@types/react": 19.1.0
  "@types/react-dom": 19.1.0
  "@vitejs/plugin-react": 4.3.4

