packages:
  - apps/*
  - frontend/*
  - shared/*


catalog:
  i18next: 24.2.3
  i18next-chained-backend: 4.6.2
  i18next-http-backend: 3.0.2
  i18next-resources-to-backend: 1.2.1
  immer: 10.1.1
  json-schema-to-zod: 2.6.0
  lucide-react: 0.474.0
  motion: 12.6.3
  nanoid: 5.1.5
  react: 19.1.0
  react-dom: 19.1.0
  react-error-boundary: 5.0.0
  rollup-plugin-visualizer: 5.14.0
  vite: 6.0.9
  vite-tsconfig-paths: 5.1.4
  postcss: 8.5.1
  typescript: 5.7.3
  tailwindcss: 3.4.14
  vite-plugin-bundlesize: 0.1.0
  zod: 3.24.1
  zustand: 5.0.3
  "@casl/react": 5.0.0
  "@incmix/utils": 0.1.0
  "@radix-ui/themes": 3.2.1
  "@tailwindcss/typography": 0.5.16
  "@tanstack/zod-form-adapter": 0.42.1
  "@tanstack/react-form": 1.2.3
  "@tanstack/react-query": 5.71.1
  "@tanstack/react-router": 1.114.29
  "@tanstack/react-table": 8.21.2
  "@tiptap/react": 2.11.5
  "@tiptap/starter-kit": 2.11.5
  "@types/react": 19.1.0
  "@types/react-dom": 19.1.0
  "@vitejs/plugin-react": 4.3.4

