packages:
  - apps/*
  - frontend/*
  - shared/*


catalog:
  lucide-react: 0.474.0
  react: 19.0.0
  react-dom: 19.0.0
  rollup-plugin-visualizer: 5.14.0
  vite: 6.0.9
  vite-tsconfig-paths: 5.1.4
  postcss: 8.5.1
  typescript: 5.7.3
  tailwindcss: 3.4.14
  vite-plugin-bundlesize: 0.1.0
  zod: 3.24.1
  nanoid: "5.0.9"
  "@radix-ui/themes": 3.2.0
  "@tanstack/react-query": 5.65.1
  "@tanstack/react-router": 1.98.3
  "@types/react": 19.0.0
  "@types/react-dom": 19.0.0
  "@vitejs/plugin-react": 4.3.4
  "@incmix/utils": 0.1.0

