import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Avatar, Box, Card, DropdownMenu, Flex, Heading, IconButton, Progress, Text, } from "@/components/base";
/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
import { Clock, Ellipsis, Pencil, Trash2, UserPlus } from "lucide-react";
import { iconSize } from "../../icons/icon";
import { useProjectDrawer } from "../hooks/use-project-drawer";
export function ProjectCard({ project, onAddMember, onAddDueDate, onDelete, isListFilter, }) {
    const { handleDrawerOpen } = useProjectDrawer();
    return (_jsxs(Card.Root, { onClick: () => {
            if (isListFilter) {
                handleDrawerOpen(project.id.toString());
            }
        }, className: `flex flex-col gap-4 rounded-lg p-5 ${isListFilter && "cursor-pointer"}`, children: [_jsxs(Flex, { align: "center", justify: "between", children: [_jsxs(Flex, { align: "center", gap: "3", children: [_jsx(Box, { className: "relative grid h-14 w-14 place-content-center rounded-xl border-2 border-gray-4 p-2", children: _jsx("img", { src: project.logo, alt: project.title, width: 40, height: 40, className: "object-contain" }) }), _jsxs(Box, { children: [_jsx(Heading, { as: "h3", className: "font-medium text-gray-12", size: "3", children: project.title }), _jsx(Text, { as: "p", className: "text-gray-11 text-sm", children: project.company })] })] }), !isListFilter && (_jsxs(DropdownMenu.Root, { children: [_jsx(DropdownMenu.Trigger, { className: " cursor-pointer", children: _jsx(IconButton, { className: "bg-transparent text-gray-10", children: _jsx(Ellipsis, {}) }) }), _jsxs(DropdownMenu.Content, { align: "end", className: "w-[180px] p-0", children: [_jsxs(DropdownMenu.Item, { onClick: () => project?.id && handleDrawerOpen(project.id.toString()), className: "flex items-center gap-2", children: [_jsx(Pencil, { size: 16 }), "Edit"] }), _jsxs(DropdownMenu.Item, { onClick: () => onAddMember(project), className: "flex items-center gap-2", children: [_jsx(UserPlus, { size: 16 }), "Add Member"] }), _jsxs(DropdownMenu.Item, { onClick: () => onAddDueDate(project), className: "flex items-center gap-2", children: [_jsx(Clock, { size: 16 }), "Add Due Date"] }), _jsx(DropdownMenu.Separator, {}), _jsxs(DropdownMenu.Item, { color: "red", onClick: () => onDelete(project.id), children: [_jsx(Trash2, { size: 16 }), "Delete Project"] })] })] }))] }), !isListFilter && (_jsx(Text, { as: "p", className: "text-gray-11 text-sm", children: project.description })), !isListFilter && (_jsxs(Box, { children: [_jsxs(Flex, { align: "center", justify: "between", className: "mb-1", children: [_jsx(Text, { as: "span", className: "text-gray-11 text-sm", children: "Progress" }), _jsxs(Text, { as: "span", className: "text-gray-11 text-sm", children: [project.progress, "%"] })] }), _jsx(Progress, { value: project.progress, color: "green", size: "2" })] })), _jsxs(Flex, { align: "center", justify: "between", className: "mt-auto pt-2", children: [_jsxs(Flex, { align: "center", gap: "1", className: "rounded-md bg-gray-3 p-2 font-medium text-gray-11", children: [_jsx(Clock, { className: `${iconSize}` }), _jsxs(Text, { as: "span", className: "text-sm ", children: [project.timeLeft, " ", project.timeType, " left"] })] }), _jsx(Flex, { gap: "1", children: project.members.slice(0, 3).map((member) => (_jsx(Box, { className: "h-8 w-8 overflow-hidden rounded-full", children: _jsx(Avatar, { src: member.avatar, name: member.name }) }, member.id))) })] })] }));
}
//# sourceMappingURL=project-card.js.map