import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Button, Flex, IconButton, Label, Switch, Tabs, } from "@/components/base";
import { iconSize } from "@/components/icons/icon";
import { X } from "lucide-react";
import { useState } from "react";
import { projectFolders } from "../data";
import { ProjectActionsMenu } from "./project-actions-menu";
export function ProjectDetails({ projectId, onClose }) {
    const [settings, setSettings] = useState({
        fileSharing: true,
        backup: false,
        sync: false,
    });
    const fileData = projectFolders.find((file) => file.id === projectId);
    if (!fileData) {
        return (_jsxs(Flex, { className: "h-full items-center justify-center", direction: "column", children: [_jsx("p", { className: "text-muted-foreground", children: "Project not found" }), _jsx(Button, { onClick: onClose, className: "mt-4", children: "Close" })] }));
    }
    return (_jsxs(Flex, { className: "h-full", direction: "column", children: [_jsxs(Flex, { className: "border-gray-4 border-b p-4", align: "center", justify: "between", children: [_jsx(Flex, { align: "center", gap: "2", children: _jsx("h2", { className: "truncate font-semibold text-lg", children: fileData?.name }) }), _jsxs(Flex, { align: "center", gap: "2", children: [_jsx(ProjectActionsMenu, { projectId: fileData?.id, className: "h-6 w-6 cursor-pointer" }), _jsx(IconButton, { variant: "ghost", className: "h-6 w-6 cursor-pointer", onClick: onClose, children: _jsx(X, { className: `${iconSize}` }) })] })] }), _jsx(Flex, { direction: "column", align: "center", justify: "center", className: " rounded-lg p-4 ", children: fileData?.type === "folder" ? (_jsxs("div", { className: "flex flex-col items-center justify-center py-4", children: [fileData?.openIcon && (_jsx(fileData.openIcon, { className: "mb-2 h-16 w-16 text-blue-500" })), _jsx("p", { className: "text-muted-foreground text-xs", children: "Folder with multiple items" })] })) : (_jsx("div", { className: "flex flex-col items-center justify-center py-4", children: _jsx("p", { className: "text-muted-foreground text-xs", children: "Preview not available" }) })) }), _jsxs(Tabs.Root, { defaultValue: "preview", className: "flex-1", children: [_jsxs(Tabs.List, { className: "mt-4 flex w-full justify-between ", children: [_jsx(Tabs.Trigger, { value: "preview", className: "w-full flex-1 cursor-pointer", children: "Preview" }), _jsx(Tabs.Trigger, { value: "comments", className: "w-full flex-1 cursor-pointer", children: "Comments" })] }), _jsx(Tabs.Content, { value: "preview", className: "flex-1 px-8 py-4 ", children: _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("h3", { className: "font-medium text-sm", children: "INFO" }), _jsxs(_Fragment, { children: [_jsxs("div", { className: "flex justify-between gap-2 text-sm", children: [_jsx("div", { className: "text-muted-foreground", children: "Type" }), _jsx("div", { className: "font-medium capitalize", children: fileData?.type === "folder" ? "Folder" : fileData?.type })] }), _jsxs("div", { className: "flex justify-between gap-2 text-sm", children: [_jsx("div", { className: "text-muted-foreground", children: "Size" }), _jsx("div", { className: "font-medium", children: fileData?.size
                                                                ? `${fileData.size.value} ${fileData.size.unit}`
                                                                : "N/A" })] }), _jsxs("div", { className: "flex justify-between gap-2 text-sm", children: [_jsx("div", { className: "text-muted-foreground", children: "Owner" }), _jsx("div", { className: "font-medium", children: fileData?.owner })] }), _jsxs("div", { className: "flex justify-between gap-2 text-sm", children: [_jsx("div", { className: "text-muted-foreground", children: "Location" }), _jsx("div", { className: "font-medium", children: fileData?.location })] }), _jsxs("div", { className: "flex justify-between gap-2 text-sm", children: [_jsx("div", { className: "text-muted-foreground", children: "Modified" }), _jsx("div", { className: "font-medium", children: fileData?.modified })] }), _jsxs("div", { className: "flex justify-between gap-2 text-sm", children: [_jsx("div", { className: "text-muted-foreground", children: "Created" }), _jsx("div", { className: "font-medium", children: fileData?.created })] })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h3", { className: "font-medium text-sm", children: "SETTINGS" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx(Label, { htmlFor: "file-sharing", className: "text-sm", children: "File Sharing" }), _jsx(Switch, { id: "file-sharing", checked: settings.fileSharing, onCheckedChange: (checked) => setSettings((prev) => ({ ...prev, fileSharing: checked })) })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(Label, { htmlFor: "backup", className: "text-sm", children: "Backup" }), _jsx(Switch, { id: "backup", checked: settings.backup, onCheckedChange: (checked) => setSettings((prev) => ({ ...prev, backup: checked })) })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(Label, { htmlFor: "sync", className: "text-sm", children: "Sync" }), _jsx(Switch, { id: "sync", checked: settings.sync, onCheckedChange: (checked) => setSettings((prev) => ({ ...prev, sync: checked })) })] })] })] })] }) }), _jsx(Tabs.Content, { value: "comments", className: "flex-1 pt-4", children: _jsx("div", { className: "flex h-40 flex-col items-center justify-center text-muted-foreground", children: _jsx("p", { className: "text-sm", children: "No comments yet" }) }) })] })] }));
}
//# sourceMappingURL=project-details.js.map