import { dashboardImg } from "./assets";
import { LayoutPreset } from "./dashboard-types";

export const initialLayouts = {
  lg: [
    {
      w: 3,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
      layouts: [
        {
          w: 12,
          h: 12,
          x: 0,
          y: 0,
          i: "grid-a|0",
          componentName:"new-tasks",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 11,
          x: 0,
          y: 12,
          i: "grid-a|1",
          componentName:"total-tasks",
          moved: false,
          static: false,
        },
      ]
    },
    {
      w: 5,
      h: 24,
      x: 3,
      y: 0,
      i: "c",
      componentName:"project-widget",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 25,
      x: 0,
      y: 24,
      i: "grid-b",
      moved: false,
      static: false,
      layouts: [
          {
            w: 6,
            h: 27,
            x: 0,
            y: 0,
            i: "grid-b|0",
            componentName:"statistic-widget",
            moved: false,
            static: false,
          },
          {
            w: 6,
            h: 27,
            x: 6,
            y: 0,
            i: "grid-b|1",
            componentName:"active-task",
            moved: false,
            static: false,
          },
        ]
    },
    {
      w: 8,
      h: 19,
      x: 0,
      y: 49,
      i: "f",
      componentName:"total-project",
      moved: false,
      static: false,
    },
    {
      w: 12,
      h: 26,
      x: 0,
      y: 68,
      i: "g",
      componentName:"posting-task",
      moved: false,
      static: false,
    },
    {
      w: 4,
      h: 68,
      x: 8,
      y: 0,
      i: "h",
      componentName:"user-panel-overview",
      moved: false,
      static: false,
    },
  ],
  md: [
    {
      w: 3,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
    },
    {
      w: 5,
      h: 24,
      x: 3,
      y: 0,
      i: "c",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 25,
      x: 0,
      y: 24,
      i: "grid-b",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 17,
      x: 0,
      y: 49,
      i: "f",
      moved: false,
      static: false,
    },
    {
      w: 12,
      h: 25,
      x: 0,
      y: 66,
      i: "g",
      moved: false,
      static: false,
    },
    {
      w: 4,
      h: 66,
      x: 8,
      y: 0,
      i: "h",
      moved: false,
      static: false,
    },
  ],
  sm: [
    {
      w: 6,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
    },
    {
      w: 6,
      h: 23,
      x: 0,
      y: 24,
      i: "c",
      moved: false,
      static: false,
    },
    {
      w: 12,
      h: 25,
      x: 0,
      y: 70,
      i: "grid-b",
      moved: false,
      static: false,
    },
    {
      w: 6,
      h: 23,
      x: 0,
      y: 47,
      i: "f",
      moved: false,
      static: false,
    },
    {
      w: 12,
      h: 25,
      x: 0,
      y: 95,
      i: "g",
      moved: false,
      static: false,
    },
    {
      w: 6,
      h: 70,
      x: 6,
      y: 0,
      i: "h",
      moved: false,
      static: false,
    },
  ],
  xs: [
    {
      w: 6,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
    },
    {
      w: 6,
      h: 23,
      x: 0,
      y: 24,
      i: "c",
      moved: false,
      static: false,
    },
    {
      w: 12,
      h: 25,
      x: 0,
      y: 70,
      i: "grid-b",
      moved: false,
      static: false,
    },
    {
      w: 6,
      h: 23,
      x: 0,
      y: 47,
      i: "f",
      moved: false,
      static: false,
    },
    {
      w: 12,
      h: 25,
      x: 0,
      y: 95,
      i: "g",
      moved: false,
      static: false,
    },
    {
      w: 6,
      h: 70,
      x: 6,
      y: 0,
      i: "h",
      moved: false,
      static: false,
    },
  ],
  xxs: [
    {
      w: 3,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 12,
      x: 0,
      y: 6,
      i: "c",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 25,
      x: 0,
      y: 24,
      i: "grid-b",
      moved: false,
      static: false,
      compactType: "horizontal",
    },
    {
      w: 14,
      h: 9,
      x: 0,
      y: 42,
      i: "f",
      moved: false,
      static: false,
    },
    {
      w: 14,
      h: 13,
      x: 0,
      y: 51,
      i: "g",
      moved: false,
      static: false,
    },
    {
      w: 6,
      h: 42,
      x: 8,
      y: 0,
      i: "h",
      moved: false,
      static: false,
    },
  ],
};

export const presetLayouts: LayoutPreset[] = [
  {
    id: "default",
    name: "Default",
    description: "Standard dashboard layout with widgets arranged in a grid",
    image: dashboardImg.defaultPreset,
    mainLayouts: {
      lg: [
        {
          w: 3,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName:"new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName:"total-tasks",
              moved: false,
              static: false,
            },
          ]
        },
        {
          w: 5,
          h: 24,
          x: 3,
          y: 0,
          i: "c",
          componentName:"project-widget",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 25,
          x: 0,
          y: 24,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
              {
                w: 6,
                h: 27,
                x: 0,
                y: 0,
                i: "grid-b|0",
                componentName:"statistic-widget",
                moved: false,
                static: false,
              },
              {
                w: 6,
                h: 27,
                x: 6,
                y: 0,
                i: "grid-b|1",
                componentName:"active-task",
                moved: false,
                static: false,
              },
            ]
        },
        {
          w: 8,
          h: 19,
          x: 0,
          y: 49,
          i: "f",
          componentName:"total-project",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 26,
          x: 0,
          y: 68,
          i: "g",
          componentName:"posting-task",
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 68,
          x: 8,
          y: 0,
          i: "h",
          componentName:"user-panel-overview",
          moved: false,
          static: false,
        },
      ],
      md: [
        {
          w: 3,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
        },
        {
          w: 5,
          h: 24,
          x: 3,
          y: 0,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 25,
          x: 0,
          y: 24,
          i: "grid-b",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 17,
          x: 0,
          y: 49,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 66,
          i: "g",
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 66,
          x: 8,
          y: 0,
          i: "h",
          moved: false,
          static: false,
        },
      ],
      sm: [
        {
          w: 6,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 24,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 70,
          i: "grid-b",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 47,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 95,
          i: "g",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 70,
          x: 6,
          y: 0,
          i: "h",
          moved: false,
          static: false,
        },
      ],
      xs: [
        {
          w: 6,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 24,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 70,
          i: "grid-b",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 47,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 95,
          i: "g",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 70,
          x: 6,
          y: 0,
          i: "h",
          moved: false,
          static: false,
        },
      ],
      xxs: [
        {
          w: 3,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 12,
          x: 0,
          y: 6,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 25,
          x: 0,
          y: 24,
          i: "grid-b",
          moved: false,
          static: false,
          compactType: "horizontal",
        },
        {
          w: 14,
          h: 9,
          x: 0,
          y: 42,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 14,
          h: 13,
          x: 0,
          y: 51,
          i: "g",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 42,
          x: 8,
          y: 0,
          i: "h",
          moved: false,
          static: false,
        },
      ],
    },
  },
  {
    id: "sidebar",
    name: "Sidebar",
    description: "Layout with a sidebar and main content area",
    image: dashboardImg.presetsImg,
    mainLayouts: {
      lg: [
        {
          w: 8,
          h: 13,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 12,
              x: 6,
              y: 0,
              i: "grid-a|1",
              moved: false,
              static: false,
            },
          ],
        },
        {
          w: 4,
          h: 26,
          x: 0,
          y: 13,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 28,
          x: 0,
          y: 39,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 27,
              x: 0,
              y: 0,
              i: "grid-b|0",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 27,
              x: 6,
              y: 0,
              i: "grid-b|1",
              moved: false,
              static: false,
            },
          ]
        },
        {
          w: 4,
          h: 26,
          x: 4,
          y: 13,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 26,
          x: 0,
          y: 67,
          i: "g",
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 67,
          x: 8,
          y: 0,
          i: "h",
          moved: false,
          static: false,
        },
      ],
      md: [
        {
          w: 8,
          h: 13,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 24,
          x: 0,
          y: 13,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 78,
          i: "grid-b",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 17,
          x: 0,
          y: 37,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 24,
          x: 0,
          y: 54,
          i: "g",
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 78,
          x: 8,
          y: 0,
          i: "h",
          moved: false,
          static: false,
        },
      ],
      sm: [
        {
          w: 8,
          h: 13,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 24,
          x: 0,
          y: 13,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 78,
          i: "grid-b",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 17,
          x: 0,
          y: 37,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 24,
          x: 0,
          y: 54,
          i: "g",
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 78,
          x: 8,
          y: 0,
          i: "h",
          moved: false,
          static: false,
        },
      ],
      xs: [
        {
          w: 6,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 24,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 70,
          i: "grid-b",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 47,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 95,
          i: "g",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 70,
          x: 6,
          y: 0,
          i: "h",
          moved: false,
          static: false,
        },
      ],
      xxs: [
        {
          w: 3,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 12,
          x: 0,
          y: 6,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 25,
          x: 0,
          y: 24,
          i: "grid-b",
          moved: false,
          static: false,
          compactType: "horizontal",
        },
        {
          w: 14,
          h: 9,
          x: 0,
          y: 42,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 14,
          h: 13,
          x: 0,
          y: 51,
          i: "g",
          moved: false,
          static: false,
        },
        {
          w: 6,
          h: 42,
          x: 8,
          y: 0,
          i: "h",
          moved: false,
          static: false,
        },
      ],
    },
  },
];