import { dashboardImg } from "./assets";
import { LayoutPreset } from "./dashboard-types";

export const initialLayouts = {
  lg: [
    {
      w: 3,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
      layouts: [
        {
          w: 12,
          h: 12,
          x: 0,
          y: 0,
          i: "grid-a|0",
          componentName:"new-tasks",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 11,
          x: 0,
          y: 12,
          i: "grid-a|1",
          componentName:"total-tasks",
          moved: false,
          static: false,
        },
      ]
    },
    {
      w: 5,
      h: 24,
      x: 3,
      y: 0,
      i: "f",
      componentName:"project-widget",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 19,
      x: 0,
      y: 49,
      i: "c",
      componentName:"total-project",
      moved: false,
      static: false,
    },
  ],
  md: [
    {
      w: 3,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
      layouts: [
        {
          w: 12,
          h: 12,
          x: 0,
          y: 0,
          i: "grid-a|0",
          componentName:"new-tasks",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 11,
          x: 0,
          y: 12,
          i: "grid-a|1",
          componentName:"total-tasks",
          moved: false,
          static: false,
        },
      ]
    },
    {
      w: 5,
      h: 24,
      x: 3,
      y: 0,
      i: "f",
      componentName:"project-widget",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 19,
      x: 0,
      y: 49,
      i: "c",
      componentName:"total-project",
      moved: false,
      static: false,
    },
  ],
  sm:[
    {
      w: 3,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
      layouts: [
        {
          w: 12,
          h: 12,
          x: 0,
          y: 0,
          i: "grid-a|0",
          componentName:"new-tasks",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 11,
          x: 0,
          y: 12,
          i: "grid-a|1",
          componentName:"total-tasks",
          moved: false,
          static: false,
        },
      ]
    },
    {
      w: 5,
      h: 24,
      x: 3,
      y: 0,
      i: "f",
      componentName:"project-widget",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 19,
      x: 0,
      y: 49,
      i: "c",
      componentName:"total-project",
      moved: false,
      static: false,
    },
  ],
  xs:[
    {
      w: 3,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
      layouts: [
        {
          w: 12,
          h: 12,
          x: 0,
          y: 0,
          i: "grid-a|0",
          componentName:"new-tasks",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 11,
          x: 0,
          y: 12,
          i: "grid-a|1",
          componentName:"total-tasks",
          moved: false,
          static: false,
        },
      ]
    },
    {
      w: 5,
      h: 24,
      x: 3,
      y: 0,
      i: "f",
      componentName:"project-widget",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 19,
      x: 0,
      y: 49,
      i: "c",
      componentName:"total-project",
      moved: false,
      static: false,
    },
  ],
  xxs:[
    {
      w: 3,
      h: 24,
      x: 0,
      y: 0,
      i: "grid-a",
      moved: false,
      static: false,
      layouts: [
        {
          w: 12,
          h: 12,
          x: 0,
          y: 0,
          i: "grid-a|0",
          componentName:"new-tasks",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 11,
          x: 0,
          y: 12,
          i: "grid-a|1",
          componentName:"total-tasks",
          moved: false,
          static: false,
        },
      ]
    },
    {
      w: 5,
      h: 24,
      x: 3,
      y: 0,
      i: "f",
      componentName:"project-widget",
      moved: false,
      static: false,
    },
    {
      w: 8,
      h: 19,
      x: 0,
      y: 49,
      i: "c",
      componentName:"total-project",
      moved: false,
      static: false,
    },
  ],
};

export const presetLayouts: LayoutPreset[] = [
  {
    id: "default",
    name: "Default",
    description: "Standard dashboard layout with widgets arranged in a grid",
    lightImage: dashboardImg.lightDefaultPreset,
    darkImage: dashboardImg.darkDefaultPreset,
    mainLayouts: {
      lg: [
        {
          w: 3,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "tp",
          x: 6,
          y: 44,
          w: 2,
          h: 11,
          moved: false,
          static: false,
          componentName: "tasks-in-progress",
        },
        {
          i: "s",
          x: 4,
          y: 44,
          w: 2,
          h: 11,
          moved: false,
          static: false,
          componentName: "tasks-done",
        },
        {
          i: "p",
          x: 2,
          y: 44,
          w: 2,
          h: 11,
          moved: false,
          static: false,
          componentName: "new-tasks-chart",
        },
        {
          i: "q",
          x: 0,
          y: 44,
          w: 2,
          h: 11,
          moved: false,
          static: false,
          componentName: "total-tasks-chart",
        },
        {
          i: "o",
          x: 0,
          y: 24,
          w: 8,
          h: 20,
          moved: false,
          static: false,
          componentName: "project-timeline",
        },
        {
          i: "rc",
          x: 8,
          y: 30,
          w: 4,
          h: 47,
          moved: false,
          static: false,
          componentName: "recent-activity",
        },
        {
          i: "usp",
          x: 8,
          y: 0,
          w: 4,
          h: 6,
          moved: false,
          static: false,
          componentName: "user-profile",
        },
        {
          i: "cld",
          x: 8,
          y: 6,
          w: 4,
          h: 24,
          moved: false,
          static: false,
          componentName: "calendar",
        },
        {
          w: 5,
          h: 24,
          x: 3,
          y: 0,
          i: "c",
          componentName: "project-widget",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 22,
          x: 0,
          y: 55,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 21,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 21,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "st2",
          x: 0,
          y: 77,
          w: 8,
          h: 20,
          moved: false,
          static: false,
          componentName: "statistics2",
        },
        {
          w: 4,
          h: 20,
          x: 8,
          y: 77,
          i: "f",
          componentName: "total-project",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 26,
          x: 0,
          y: 97,
          i: "g",
          componentName: "posting-task",
          moved: false,
          static: false,
        },
      ],
      md: [
        {
          w: 3,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "tp",
          x: 3,
          y: 0,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "tasks-in-progress",
        },
        {
          i: "s",
          x: 3,
          y: 14,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "tasks-done",
        },
        {
          i: "p",
          x: 3,
          y: 28,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "new-tasks-chart",
        },
        {
          i: "q",
          x: 3,
          y: 42,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "total-tasks-chart",
        },
        {
          i: "o",
          x: 3,
          y: 56,
          w: 6,
          h: 20,
          moved: false,
          static: false,
          componentName: "project-timeline",
        },
        {
          i: "rc",
          x: 3,
          y: 98,
          w: 4,
          h: 38,
          moved: false,
          static: false,
          componentName: "recent-activity",
        },
        {
          i: "usp",
          x: 3,
          y: 148,
          w: 4,
          h: 6,
          moved: false,
          static: false,
          componentName: "user-profile",
        },
        {
          i: "cld",
          x: 3,
          y: 154,
          w: 4,
          h: 28,
          moved: false,
          static: false,
          componentName: "calendar",
        },
        {
          w: 5,
          h: 24,
          x: 3,
          y: 188,
          componentName: "project-widget",
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 25,
          x: 0,
          y: 212,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 21,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 21,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "st2",
          x: 0,
          y: 237,
          w: 8,
          h: 20,
          moved: false,
          static: false,
          componentName: "statistics2",
        },
        {
          w: 8,
          h: 17,
          x: 0,
          y: 257,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 274,
          i: "g",
          moved: false,
          static: false,
        },
      ],
      sm: [
        {
          w: 6,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "tp",
          x: 0,
          y: 24,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "tasks-in-progress",
        },
        {
          i: "s",
          x: 0,
          y: 38,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "tasks-done",
        },
        {
          i: "p",
          x: 0,
          y: 52,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "new-tasks-chart",
        },
        {
          i: "q",
          x: 0,
          y: 66,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "total-tasks-chart",
        },
        {
          i: "o",
          x: 0,
          y: 80,
          w: 6,
          h: 20,
          moved: false,
          static: false,
          componentName: "project-timeline",
        },
        {
          i: "rc",
          x: 0,
          y: 122,
          w: 4,
          h: 38,
          moved: false,
          static: false,
          componentName: "recent-activity",
        },
        {
          i: "usp",
          x: 0,
          y: 172,
          w: 4,
          h: 6,
          moved: false,
          static: false,
          componentName: "user-profile",
        },
        {
          i: "cld",
          x: 0,
          y: 178,
          w: 4,
          h: 28,
          moved: false,
          static: false,
          componentName: "calendar",
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 212,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 258,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 21,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 21,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "st2",
          x: 0,
          y: 235,
          w: 8,
          h: 20,
          moved: false,
          static: false,
          componentName: "statistics2",
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 255,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 303,
          i: "g",
          moved: false,
          static: false,
        },
      ],
      xs: [
        {
          w: 6,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "tp",
          x: 0,
          y: 24,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "tasks-in-progress",
        },
        {
          i: "s",
          x: 0,
          y: 38,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "tasks-done",
        },
        {
          i: "p",
          x: 0,
          y: 52,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "new-tasks-chart",
        },
        {
          i: "q",
          x: 0,
          y: 66,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "total-tasks-chart",
        },
        {
          i: "o",
          x: 0,
          y: 80,
          w: 6,
          h: 20,
          moved: false,
          static: false,
          componentName: "project-timeline",
        },
        {
          i: "rc",
          x: 0,
          y: 122,
          w: 4,
          h: 38,
          moved: false,
          static: false,
          componentName: "recent-activity",
        },
        {
          i: "usp",
          x: 0,
          y: 172,
          w: 4,
          h: 6,
          moved: false,
          static: false,
          componentName: "user-profile",
        },
        {
          i: "cld",
          x: 0,
          y: 178,
          w: 4,
          h: 28,
          moved: false,
          static: false,
          componentName: "calendar",
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 212,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 258,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 21,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 21,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "st2",
          x: 0,
          y: 235,
          w: 8,
          h: 20,
          moved: false,
          static: false,
          componentName: "statistics2",
        },
        {
          w: 6,
          h: 23,
          x: 0,
          y: 255,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 303,
          i: "g",
          moved: false,
          static: false,
        },
      ],
      xxs: [
        {
          w: 3,
          h: 24,
          x: 0,
          y: 0,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "tp",
          x: 0,
          y: 6,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "tasks-in-progress",
        },
        {
          i: "s",
          x: 0,
          y: 20,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "tasks-done",
        },
        {
          i: "p",
          x: 0,
          y: 34,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "new-tasks-chart",
        },
        {
          i: "q",
          x: 0,
          y: 48,
          w: 3,
          h: 14,
          moved: false,
          static: false,
          componentName: "total-tasks-chart",
        },
        {
          i: "o",
          x: 0,
          y: 62,
          w: 6,
          h: 20,
          moved: false,
          static: false,
          componentName: "project-timeline",
        },
        {
          i: "rc",
          x: 0,
          y: 104,
          w: 4,
          h: 38,
          moved: false,
          static: false,
          componentName: "recent-activity",
        },
        {
          i: "usp",
          x: 0,
          y: 154,
          w: 4,
          h: 6,
          moved: false,
          static: false,
          componentName: "user-profile",
        },
        {
          i: "cld",
          x: 0,
          y: 160,
          w: 4,
          h: 28,
          moved: false,
          static: false,
          componentName: "calendar",
        },
        {
          w: 8,
          h: 12,
          x: 0,
          y: 194,
          i: "c",
          moved: false,
          static: false,
        },
        {
          w: 8,
          h: 25,
          x: 0,
          y: 212,
          i: "grid-b",
          moved: false,
          static: false,
          compactType: "horizontal",
          layouts: [
            {
              w: 6,
              h: 21,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 21,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
        {
          i: "st2",
          x: 0,
          y: 230,
          w: 8,
          h: 20,
          moved: false,
          static: false,
          componentName: "statistics2",
        },
        {
          w: 14,
          h: 9,
          x: 0,
          y: 250,
          i: "f",
          moved: false,
          static: false,
        },
        {
          w: 14,
          h: 13,
          x: 0,
          y: 259,
          i: "g",
          moved: false,
          static: false,
        },
      ],
    },
  },
  {
    id: "group-template",
    name: "Group Template",
    description: "Layout with group",
    lightImage: dashboardImg.lightGrpTemplate,
    darkImage: dashboardImg.darkGrpTemplate,
    mainLayouts: {
      lg: [
        {
          i: "grid-e",
          x: 0,
          y: 0,
          w: 12,
          h: 23,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-e|1752415864118",
              x: 0,
              y: 6,
              w: 5,
              h: 16,
              moved: false,
              static: false,
              componentName: "activity-timeline",
            },
            {
              i: "grid-e|1752415879576",
              x: 0,
              y: 0,
              w: 5,
              h: 6,
              moved: false,
              static: false,
              componentName: "user-profile",
            },
            {
              i: "grid-e|1752415928559",
              x: 5,
              y: 0,
              w: 7,
              h: 22,
              moved: false,
              static: false,
              componentName: "project-timeline",
            },
          ],
        },
        {
          i: "grid-d",
          x: 3,
          y: 39,
          w: 9,
          h: 24,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-d|1752415809156",
              x: 0,
              y: 0,
              w: 12,
              h: 23,
              moved: false,
              static: false,
              componentName: "statistics2",
            },
          ],
        },
        {
          i: "grid-c",
          x: 0,
          y: 23,
          w: 12,
          h: 16,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-c|1752415685508",
              x: 3,
              y: 0,
              w: 2,
              h: 15,
              moved: false,
              static: false,
              componentName: "new-tasks-chart",
            },
            {
              i: "grid-c|1752415700946",
              x: 0,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "live-visitor",
            },
            {
              i: "grid-c|1752415726378",
              x: 5,
              y: 0,
              w: 4,
              h: 15,
              moved: false,
              static: false,
              componentName: "monthly-budget",
            },
            {
              i: "grid-c|1752415767906",
              x: 9,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "total-tasks-chart",
            },
          ],
        },
        {
          w: 3,
          h: 24,
          x: 0,
          y: 39,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          w: 12,
          h: 23,
          x: 0,
          y: 63,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 22,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 22,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
      ],
      md: [
        {
          i: "grid-e",
          x: 0,
          y: 0,
          w: 8,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-e|1752415864118",
              x: 0,
              y: 6,
              w: 5,
              h: 16,
              moved: false,
              static: false,
              componentName: "activity-timeline",
            },
            {
              i: "grid-e|1752415879576",
              x: 0,
              y: 0,
              w: 5,
              h: 6,
              moved: false,
              static: false,
              componentName: "user-profile",
            },
            {
              i: "grid-e|1752415928559",
              x: 5,
              y: 0,
              w: 7,
              h: 22,
              moved: false,
              static: false,
              componentName: "project-timeline",
            },
          ],
        },
        {
          i: "grid-d",
          x: 0,
          y: 13,
          w: 8,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-d|1752415809156",
              x: 0,
              y: 0,
              w: 12,
              h: 23,
              moved: false,
              static: false,
              componentName: "statistics2",
            },
          ],
        },
        {
          i: "grid-c",
          x: 0,
          y: 26,
          w: 8,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-c|1752415685508",
              x: 3,
              y: 0,
              w: 2,
              h: 15,
              moved: false,
              static: false,
              componentName: "new-tasks-chart",
            },
            {
              i: "grid-c|1752415700946",
              x: 0,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "live-visitor",
            },
            {
              i: "grid-c|1752415726378",
              x: 5,
              y: 0,
              w: 4,
              h: 15,
              moved: false,
              static: false,
              componentName: "monthly-budget",
            },
            {
              i: "grid-c|1752415767906",
              x: 9,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "total-tasks-chart",
            },
          ],
        },
        {
          w: 3,
          h: 24,
          x: 0,
          y: 39,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          w: 8,
          h: 25,
          x: 0,
          y: 63,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 22,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 22,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
      ],
      sm: [
        {
          i: "grid-e",
          x: 0,
          y: 0,
          w: 6,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-e|1752415864118",
              x: 0,
              y: 6,
              w: 5,
              h: 16,
              moved: false,
              static: false,
              componentName: "activity-timeline",
            },
            {
              i: "grid-e|1752415879576",
              x: 0,
              y: 0,
              w: 5,
              h: 6,
              moved: false,
              static: false,
              componentName: "user-profile",
            },
            {
              i: "grid-e|1752415928559",
              x: 5,
              y: 0,
              w: 7,
              h: 22,
              moved: false,
              static: false,
              componentName: "project-timeline",
            },
          ],
        },
        {
          i: "grid-d",
          x: 0,
          y: 13,
          w: 6,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-d|1752415809156",
              x: 0,
              y: 0,
              w: 12,
              h: 23,
              moved: false,
              static: false,
              componentName: "statistics2",
            },
          ],
        },
        {
          i: "grid-c",
          x: 0,
          y: 26,
          w: 6,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-c|1752415685508",
              x: 3,
              y: 0,
              w: 2,
              h: 15,
              moved: false,
              static: false,
              componentName: "new-tasks-chart",
            },
            {
              i: "grid-c|1752415700946",
              x: 0,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "live-visitor",
            },
            {
              i: "grid-c|1752415726378",
              x: 5,
              y: 0,
              w: 4,
              h: 15,
              moved: false,
              static: false,
              componentName: "monthly-budget",
            },
            {
              i: "grid-c|1752415767906",
              x: 9,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "total-tasks-chart",
            },
          ],
        },
        {
          w: 6,
          h: 24,
          x: 0,
          y: 39,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 109,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 22,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 22,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
      ],
      xs: [
        {
          i: "grid-e",
          x: 0,
          y: 0,
          w: 4,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-e|1752415864118",
              x: 0,
              y: 6,
              w: 5,
              h: 16,
              moved: false,
              static: false,
              componentName: "activity-timeline",
            },
            {
              i: "grid-e|1752415879576",
              x: 0,
              y: 0,
              w: 5,
              h: 6,
              moved: false,
              static: false,
              componentName: "user-profile",
            },
            {
              i: "grid-e|1752415928559",
              x: 5,
              y: 0,
              w: 7,
              h: 22,
              moved: false,
              static: false,
              componentName: "project-timeline",
            },
          ],
        },
        {
          i: "grid-d",
          x: 0,
          y: 13,
          w: 4,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-d|1752415809156",
              x: 0,
              y: 0,
              w: 12,
              h: 23,
              moved: false,
              static: false,
              componentName: "statistics2",
            },
          ],
        },
        {
          i: "grid-c",
          x: 0,
          y: 26,
          w: 4,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-c|1752415685508",
              x: 3,
              y: 0,
              w: 2,
              h: 15,
              moved: false,
              static: false,
              componentName: "new-tasks-chart",
            },
            {
              i: "grid-c|1752415700946",
              x: 0,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "live-visitor",
            },
            {
              i: "grid-c|1752415726378",
              x: 5,
              y: 0,
              w: 4,
              h: 15,
              moved: false,
              static: false,
              componentName: "monthly-budget",
            },
            {
              i: "grid-c|1752415767906",
              x: 9,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "total-tasks-chart",
            },
          ],
        },
        {
          w: 6,
          h: 24,
          x: 0,
          y: 39,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          w: 12,
          h: 25,
          x: 0,
          y: 109,
          i: "grid-b",
          moved: false,
          static: false,
          layouts: [
            {
              w: 6,
              h: 22,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 22,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
      ],
      xxs: [
        {
          i: "grid-e",
          x: 0,
          y: 0,
          w: 4,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-e|1752415864118",
              x: 0,
              y: 6,
              w: 5,
              h: 16,
              moved: false,
              static: false,
              componentName: "activity-timeline",
            },
            {
              i: "grid-e|1752415879576",
              x: 0,
              y: 0,
              w: 5,
              h: 6,
              moved: false,
              static: false,
              componentName: "user-profile",
            },
            {
              i: "grid-e|1752415928559",
              x: 5,
              y: 0,
              w: 7,
              h: 22,
              moved: false,
              static: false,
              componentName: "project-timeline",
            },
          ],
        },
        {
          i: "grid-d",
          x: 0,
          y: 13,
          w: 4,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-d|1752415809156",
              x: 0,
              y: 0,
              w: 12,
              h: 23,
              moved: false,
              static: false,
              componentName: "statistics2",
            },
          ],
        },
        {
          i: "grid-c",
          x: 0,
          y: 26,
          w: 4,
          h: 13,
          moved: false,
          static: false,
          layouts: [
            {
              i: "grid-c|1752415685508",
              x: 3,
              y: 0,
              w: 2,
              h: 15,
              moved: false,
              static: false,
              componentName: "new-tasks-chart",
            },
            {
              i: "grid-c|1752415700946",
              x: 0,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "live-visitor",
            },
            {
              i: "grid-c|1752415726378",
              x: 5,
              y: 0,
              w: 4,
              h: 15,
              moved: false,
              static: false,
              componentName: "monthly-budget",
            },
            {
              i: "grid-c|1752415767906",
              x: 9,
              y: 0,
              w: 3,
              h: 15,
              moved: false,
              static: false,
              componentName: "total-tasks-chart",
            },
          ],
        },
        {
          w: 3,
          h: 24,
          x: 0,
          y: 39,
          i: "grid-a",
          moved: false,
          static: false,
          layouts: [
            {
              w: 12,
              h: 12,
              x: 0,
              y: 0,
              i: "grid-a|0",
              componentName: "new-tasks",
              moved: false,
              static: false,
            },
            {
              w: 12,
              h: 11,
              x: 0,
              y: 12,
              i: "grid-a|1",
              componentName: "total-tasks",
              moved: false,
              static: false,
            },
          ],
        },
        {
          w: 8,
          h: 25,
          x: 0,
          y: 63,
          i: "grid-b",
          moved: false,
          static: false,
          compactType: "horizontal",
          layouts: [
            {
              w: 6,
              h: 22,
              x: 0,
              y: 0,
              i: "grid-b|0",
              componentName: "statistic-widget",
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 22,
              x: 6,
              y: 0,
              i: "grid-b|1",
              componentName: "active-task",
              moved: false,
              static: false,
            },
          ],
        },
      ],
    },
  },
];