import {
  dashboardImg,
} from "@incmix/ui";
import {
    ActiveTask,
    NewTasks,
    PostingTask,
    TotalProject,
    TotalTasksChart,
    TotalTasks,
    ProjectListWidgets,
    ProjectTimelineWidgets,
    NewTasksChart,
    UserProfile,
    CalendarWidget,
    RecentActivity,
    ActivityTimeline,
    SubscribersByCountries,
    MonthlyBudget,
    LiveVisitors,
    InProgressTask,
    DoneTasks,
    ProjectWidgets,
    StatisticWidgets,
    BarStatisticWidgets,
    ClockWidget,
    BatteryWidget,
    WeatherWidget,
    NewsWidget,
  } from "@incmix/ui/widgets";

export const sidebarComponents = [

  {
    slotId: "i",
    component: <NewTasks />,
    componentName: "new-tasks",
    darkCompImage: dashboardImg.darkNewTaskImg,
    lightCompImage: dashboardImg.lightNewTaskImg,
    dragPreviewSize:"w-16 h-16 text-xs",
    title: "New Tasks",
    tags: ["task", "new", "todo"],
    layouts: {
      lg: { w: 3, h: 14 },
      md: { w: 3, h: 14 },
      sm: { w: 3, h: 14 },
      xs: { w: 3, h: 14 },
      xxs: { w: 3, h: 14 },
    },
    className: "col-span-3",
  },
  {
    slotId: "p",
    component: <NewTasksChart />,
    componentName: "new-tasks-chart",
    darkCompImage: dashboardImg.darkNewTaskChartImg,
    lightCompImage: dashboardImg.lightNewTaskChartImg,
    title: "New Tasks Chart",
    tags: ["task", "new", "todo"],
    layouts: {
      lg: { w: 3, h: 14 },
      md: { w: 3, h: 14 },
      sm: { w: 3, h: 14 },
      xs: { w: 3, h: 14 },
      xxs: { w: 3, h: 14 },
    },
    className: "col-span-3",
  },
  {
    slotId: "h",
    component: <TotalTasks />,
    componentName: "total-tasks",
    darkCompImage: dashboardImg.darkTotalTasksImg,
    lightCompImage: dashboardImg.lightTotalTasksImg,
    title: "Total Tasks",
    tags: ["task", "total", "summary"],
    layouts: {
      lg: { w: 3, h: 14 },
      md: { w: 3, h: 14 },
      sm: { w: 3, h: 14 },
      xs: { w: 3, h: 14 },
      xxs: { w: 3, h: 14 },
    },
    className: "col-span-3",
  },
  {
    slotId: "q",
    component: <TotalTasksChart />,
    componentName: "total-tasks-chart",
    darkCompImage: dashboardImg.darkTotalTaskChartImg,
    lightCompImage: dashboardImg.lightTotalTaskChartImg,
    title: "Total Tasks Chart",
    tags: ["task", "total", "summary"],
    layouts: {
      lg: { w: 3, h: 14 },
      md: { w: 3, h: 14 },
      sm: { w: 3, h: 14 },
      xs: { w: 3, h: 14 },
      xxs: { w: 3, h: 14 },
    },
    className: "col-span-3",
  },
  {
    slotId: "tp",
    component: <InProgressTask />,
    componentName: "tasks-in-progress",
    darkCompImage: dashboardImg.darkInProgressTaskImg,
    lightCompImage: dashboardImg.lightInProgressTaskImg,
    title: "Tasks In Progress",
    tags: ["task", "total", "in-progress"],
    layouts: {
      lg: { w: 3, h: 14 },
      md: { w: 3, h: 14 },
      sm: { w: 3, h: 14 },
      xs: { w: 3, h: 14 },
      xxs: { w: 3, h: 14 },
    },
    className: "col-span-3",
  },
  {
    slotId: "s",
    component: <DoneTasks />,
    componentName: "tasks-done",
    darkCompImage: dashboardImg.darkDoneTaskImg,
    lightCompImage: dashboardImg.lightDoneTaskImg,
    title: "Tasks Done",
    tags: ["task", "task-done", "done"],
    layouts: {
      lg: { w: 3, h: 14 },
      md: { w: 3, h: 14 },
      sm: { w: 3, h: 14 },
      xs: { w: 3, h: 14 },
      xxs: { w: 3, h: 14 },
    },
    className: "col-span-3",
  },
  {
    slotId: "usp",
    component: <UserProfile />,
    componentName: "user-profile",
    darkCompImage: dashboardImg.darkProfileImg,
    lightCompImage: dashboardImg.lightProfileImg,
    title: "Profile",
    tags: ["profile","user-profile"],
    layouts: {
      lg: { w: 4, h: 6 },
      md: { w: 4, h: 6 },
      sm: { w: 4, h: 6 },
      xs: { w: 4, h: 6 },
      xxs: { w: 4, h: 6 },
    },
    className: "col-span-6",
  },
  {
    slotId: "m",
    component: <TotalProject />,
    componentName: "total-project",
    darkCompImage: dashboardImg.darkTotalProjectImg,
    lightCompImage: dashboardImg.lightTotalProjectImg,
    title: "Total Project",
    tags: ["project", "total", "summary"],
    layouts: {
      lg: { w: 4, h: 22 },
      md: { w: 4, h: 22 },
      sm: { w: 4, h: 22 },
      xs: { w: 4, h: 22 },
      xxs: { w: 4, h: 22 },
    },
    className:"col-span-6"
  },
 
  {
    slotId: "k",
    component: <StatisticWidgets />,
    componentName: "statistic-widget",
    darkCompImage: dashboardImg.darkStatisticsImg,
    lightCompImage: dashboardImg.lightStatisticsImg,
    title: "Statistic Widgets",
    tags: ["statistics", "analytics", "data"],
    layouts: {
      lg: { w: 4, h: 22 },
      md: { w: 4, h: 22 },
      sm: { w: 4, h: 22 },
      xs: { w: 4, h: 22 },
      xxs: { w: 4, h: 22 },
    },
    className:"col-span-6"
  },
  {
    slotId: "l",
    component: <ActiveTask />,
    componentName: "active-task",
    darkCompImage: dashboardImg.darkActiveTaskImg,
    lightCompImage: dashboardImg.lightActiveTaskImg,
    title: "Active Task",
    tags: ["task", "active", "ongoing"],
    layouts: {
      lg: { w: 4, h: 22 },
      md: { w: 4, h: 22 },
      sm: { w: 4, h: 22 },
      xs: { w: 4, h: 22 },
      xxs: { w: 4, h: 22 },
    },
    className:"col-span-6"
  },
  {
    slotId: "j",
    component: <ProjectWidgets />,
    componentName: "project-widget",
    darkCompImage: dashboardImg.darkProjectChartImg,
    lightCompImage: dashboardImg.lightProjectChartImg,
    title: "Project Widgets",
    tags: ["project", "widget", "summary"],
    layouts: {
      lg: { w: 5, h: 24 },
      md: { w: 5, h: 24 },
      sm: { w: 5, h: 24 },
      xs: { w: 5, h: 24 },
      xxs: { w: 5, h: 24 },
    },
    className:"col-span-6"
  },
  {
    slotId: "n",
    component: <PostingTask />,
    componentName: "posting-task",
    darkCompImage: dashboardImg.darkPostingTaskImg,
    lightCompImage: dashboardImg.lightPostingTaskImg,
    title: "Posting Task",
    tags: ["task", "posting", "create"],
    layouts: {
      lg: { w: 12, h: 25 },
      md: { w: 12, h: 25 },
      sm: { w: 12, h: 25 },
      xs: { w: 12, h: 25 },
      xxs: { w: 12, h: 25 },
    },
    className:"col-span-12"
  },
  {
    slotId: "o",
    component: <ProjectTimelineWidgets />,
    componentName: "project-timeline",
    darkCompImage: dashboardImg.darkProjectTimelineImg,
    lightCompImage: dashboardImg.lightProjectTimelineImg,
    title: "Project Timeline",
    tags: ["project", "timeline", "summary", "project-timeline"],
    layouts: {
      lg: { w: 6, h: 20 },
      md: { w: 6, h: 20 },
      sm: { w: 6, h: 20 },
      xs: { w: 6, h: 20 },
      xxs: { w: 6, h: 20 },
    },
    className:"col-span-8"
  },
  {
    slotId: "r",
    component: <ProjectListWidgets />,
    componentName: "project-list",
    darkCompImage: dashboardImg.darkProjectListImg,
    lightCompImage: dashboardImg.lightProjectListImg,
    title: "Project List",
    tags: ["project", "list", "project-list"],
    layouts: {
      lg: { w: 3, h: 20 },
      md: { w: 3, h: 20 },
      sm: { w: 3, h: 20 },
      xs: { w: 3, h: 20 },
      xxs: { w: 3, h: 20 },
    },
    className:"col-span-4"
  },

  {
    slotId: "cld",
    component: <CalendarWidget storageKey="calendar" />,
    componentName: "calendar",
    darkCompImage: dashboardImg.darkCalendarImg,
    lightCompImage: dashboardImg.lightCalendarImg,
    title: "Calendar",
    tags: ["calendar"],
    layouts: {
      lg: { w: 4, h: 28 },
      md: { w: 4, h: 28 },
      sm: { w: 4, h: 28 },
      xs: { w: 4, h: 28 },
      xxs: { w: 4, h: 28 },
    },
    className:"col-span-6"
  },
  {
    slotId: "st2",
    component: <BarStatisticWidgets />,
    componentName: "statistics2",
    darkCompImage: dashboardImg.darkStatisticsImg2,
    lightCompImage: dashboardImg.lightStatisticsImg2,
    title: "Statistics 2",
    tags: ["statistics2"],
    layouts: {
      lg: { w: 8, h: 20 },
      md: { w: 8, h: 20 },
      sm: { w: 8, h: 20 },
      xs: { w: 8, h: 20 },
      xxs: { w: 8, h: 20 },
    },
    className:"col-span-6"
  },
  {
    slotId: "rc",
    component: <RecentActivity />,
    componentName: "recent-activity",
    darkCompImage: dashboardImg.darkRecentActivityImg,
    lightCompImage: dashboardImg.lightRecentActivityImg,
    title: "Recent Activity",
    tags: ["activity", "recent", "recent-activity"],
    layouts: {
      lg: { w: 4, h: 38 },
      md: { w: 4, h: 38 },
      sm: { w: 4, h: 38 },
      xs: { w: 4, h: 38 },
      xxs: { w: 4, h: 38 },
    },
    className:"col-span-4"
  },
  {
    slotId: "csbr",
    component: <SubscribersByCountries />,
    componentName: "countries-subscriber",
    darkCompImage: dashboardImg.darkSubscriberImg,
    lightCompImage: dashboardImg.lightSubscriberImg,
    title: "Countries Subscriber",
    tags: ["subscriber","countries-subscriber"],
    layouts: {
      lg: { w: 5, h: 24 },
      md: { w: 5, h: 24 },
      sm: { w: 5, h: 24 },
      xs: { w: 5, h: 24 },
      xxs: { w: 5, h: 24 },
    },
    className:"col-span-8"
  },
  {
    slotId: "lv",
    component: <LiveVisitors />,
    componentName: "live-visitor",
    darkCompImage: dashboardImg.darkLiveVisitorImg,
    lightCompImage: dashboardImg.lightLiveVisitorImg,
    title: "Live Visitor",
    tags: ["live-visitor"],
    layouts: {
      lg: { w: 5, h: 14 },
      md: { w: 5, h: 14 },
      sm: { w: 5, h: 14 },
      xs: { w: 5, h: 14 },
      xxs: { w: 5, h: 14 },
    },
    className:"col-span-6"
  },
  {
    slotId: "mb",
    component: <MonthlyBudget />,
    componentName: "monthly-budget",
    darkCompImage: dashboardImg.darkMonthlyBudgetImg,
    lightCompImage: dashboardImg.lightMonthlyBudgetImg,
    title: "Monthly Budget",
    tags: ["monthly-budget"],
    layouts: {
      lg: { w: 5, h: 15 },
      md: { w: 5, h: 15 },
      sm: { w: 5, h: 15 },
      xs: { w: 5, h: 15 },
      xxs: { w: 5, h: 15 },
    },
    className:"col-span-6"
  },
  {
    slotId: "act",
    component: <ActivityTimeline />,
    componentName: "activity-timeline",
    darkCompImage: dashboardImg.darkActivityTimelineImg,
    lightCompImage: dashboardImg.lightActivityTimelineImg,
    title: "Activity Timeline",
    tags: ["activity","activity-timeline"],
    layouts: {
      lg: { w: 5, h: 16 },
      md: { w: 5, h: 16 },
      sm: { w: 5, h: 16 },
      xs: { w: 5, h: 16 },
      xxs: { w: 5, h: 16 },
    },
    className:"col-span-7"
  },
];
