import type React from "react"
import { FolderClose } from "../secondary-sidebars/file-folder/icons/folder-close"
import { FolderOpen } from "../secondary-sidebars/file-folder/icons/folder-open"

export type FileType = "folder" | "document" | "image" | "audio"
export type ItemSize = { value: number; unit: "B" | "KB" | "MB" | "GB" | "TB" }

export interface FileItem {
  id: string
  name: string
  type: FileType
  size: ItemSize
  openIcon?: React.ElementType
  closeIcon?: React.ElementType
  owner: string
  location: string
  modified: string
  created: string
  parentId?: string
  icon?: any
}

// Simplified flat data structure
export const FileManagerData = [
  // Root folders
  {
    id: "design",
    name: "Design",
  },
  {
    id: "projects",
    name: "Projects",
  },
  {
    id: "music",
    name: "Music",
  },
  {
    id: "pictures",
    name: "Pictures",
  },
  {
    id: "documents",
    name: "Documents",
  },
  {
    id: "downloads",
    name: "Downloads",
  },
]
export const projectFolders = [
  {
    id: "project1",
    parentId: "projects",
    name: "Projects_01",
    type: "folder" as const,
    size: { value: 5.8, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Projects",
    modified: "Sep 17, 2023",
    created: "Aug 20, 2023",
  },
  {
    id: "project2",
    parentId: "projects",
    name: "Projects_02",
    type: "folder" as const,
    size: { value: 3.2, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Projects",
    modified: "Sep 15, 2023",
    created: "Aug 18, 2023",
  },
  {
    id: "project3",
    parentId: "projects",

    name: "Projects_03",
    type: "folder" as const,
    size: { value: 1.5, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Projects",
    modified: "Sep 12, 2023",
    created: "Aug 15, 2023",
  },
  {
    id: "project4",
    parentId: "projects",

    name: "Projects_04",
    type: "folder" as const,
    size: { value: 1.7, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Projects",
    modified: "Sep 10, 2023",
    created: "Aug 12, 2023",
  },
  {
    id: "project5",
    parentId: "projects",

    name: "Marketing_01",
    type: "folder" as const,
    size: { value: 2.3, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Marketing",
    modified: "Sep 20, 2023",
    created: "Aug 25, 2023",
  },
  {
    id: "project6",
    parentId: "projects",

    name: "Design_Assets",
    type: "folder" as const,
    size: { value: 4.1, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Design",
    modified: "Sep 22, 2023",
    created: "Aug 30, 2023",
  },
  {
    id: "project7",
    parentId: "projects",

    name: "Client_Presentations",
    type: "folder" as const,
    size: { value: 1.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Clients",
    modified: "Sep 25, 2023",
    created: "Sep 01, 2023",
  },
  {
    id: "project8",
    parentId: "projects",

    name: "Website_Mockups",
    type: "folder" as const,
    size: { value: 3.5, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Web",
    modified: "Sep 28, 2023",
    created: "Sep 05, 2023",
  },
  {
    id: "project9",
    parentId: "projects",
    name: "Mobile_Apps",
    type: "folder" as const,
    size: { value: 2.7, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Mobile",
    modified: "Oct 01, 2023",
    created: "Sep 10, 2023",
  },
  {
    id: "project10",
    parentId: "projects",
    name: "Analytics_Reports",
    type: "folder" as const,
    size: { value: 0.8, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Reports",
    modified: "Oct 03, 2023",
    created: "Sep 15, 2023",
  },
  {
    id: "project11",
    parentId: "projects",
    name: "Social_Media",
    type: "folder" as const,
    size: { value: 1.2, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Marketing",
    modified: "Oct 05, 2023",
    created: "Sep 18, 2023",
  },
  {
    id: "project12",
    parentId: "projects",
    name: "Video_Edits",
    type: "folder" as const,
    size: { value: 7.4, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Media",
    modified: "Oct 08, 2023",
    created: "Sep 20, 2023",
  },
  {
    id: "project13",
    parentId: "projects",
    name: "Product_Photos",
    type: "folder" as const,
    size: { value: 5.2, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Products",
    modified: "Oct 10, 2023",
    created: "Sep 22, 2023",
  },
  {
    id: "project14",
    parentId: "projects",

    name: "User_Research",
    type: "folder" as const,
    size: { value: 1.1, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Research",
    modified: "Oct 12, 2023",
    created: "Sep 25, 2023",
  },
  {
    id: "project15",
    parentId: "projects",

    name: "Brand_Guidelines",
    type: "folder" as const,
    size: { value: 2.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Branding",
    modified: "Oct 15, 2023",
    created: "Sep 28, 2023",
  },
  {
    id: "project16",
    parentId: "projects",

    name: "Illustrations",
    type: "folder" as const,
    size: { value: 3.7, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Art",
    modified: "Oct 18, 2023",
    created: "Oct 01, 2023",
  },
  {
    id: "project17",
    parentId: "projects",

    name: "Prototypes",
    type: "folder" as const,
    size: { value: 1.8, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Development",
    modified: "Oct 20, 2023",
    created: "Oct 05, 2023",
  },
  {
    id: "project18",
    parentId: "projects",

    name: "Wireframes",
    type: "folder" as const,
    size: { value: 0.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "UX",
    modified: "Oct 22, 2023",
    created: "Oct 08, 2023",
  },
  {
    id: "project19",
    parentId: "projects",

    name: "Video_Edits",
    type: "folder" as const,
    size: { value: 7.4, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Media",
    modified: "Oct 08, 2023",
    created: "Sep 20, 2023",
  },
  {
    id: "project20",
    parentId: "projects",

    name: "Product_Photos",
    type: "folder" as const,
    size: { value: 5.2, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Products",
    modified: "Oct 10, 2023",
    created: "Sep 22, 2023",
  },
  {
    id: "project21",
    parentId: "projects",

    name: "User_Research",
    type: "folder" as const,
    size: { value: 1.1, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Research",
    modified: "Oct 12, 2023",
    created: "Sep 25, 2023",
  },
  {
    id: "project22",
    parentId: "projects",

    name: "Brand_Guidelines",
    type: "folder" as const,
    size: { value: 2.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Branding",
    modified: "Oct 15, 2023",
    created: "Sep 28, 2023",
  },
  {
    id: "project23",
    parentId: "projects",

    name: "Illustrations",
    type: "folder" as const,
    size: { value: 3.7, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Art",
    modified: "Oct 18, 2023",
    created: "Oct 01, 2023",
  },
  {
    id: "project24",
    parentId: "projects",

    name: "Prototypes",
    type: "folder" as const,
    size: { value: 1.8, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Development",
    modified: "Oct 20, 2023",
    created: "Oct 05, 2023",
  },
  {
    id: "project25",
    parentId: "projects",

    name: "Wireframes",
    type: "folder" as const,
    size: { value: 0.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "UX",
    modified: "Oct 22, 2023",
    created: "Oct 08, 2023",
  },
  {
    id: "project26",
    parentId: "projects",

    name: "Illustrations",
    type: "folder" as const,
    size: { value: 3.7, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Art",
    modified: "Oct 18, 2023",
    created: "Oct 01, 2023",
  },
  {
    id: "project27",
    parentId: "projects",

    name: "Prototypes",
    type: "folder" as const,
    size: { value: 1.8, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Development",
    modified: "Oct 20, 2023",
    created: "Oct 05, 2023",
  },
  {
    id: "project28",
    parentId: "projects",

    name: "Wireframes",
    type: "folder" as const,
    size: { value: 0.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "UX",
    modified: "Oct 22, 2023",
    created: "Oct 08, 2023",
  },
  {
    id: "project29",
    parentId: "projects",

    name: "Video_Edits",
    type: "folder" as const,
    size: { value: 7.4, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Media",
    modified: "Oct 08, 2023",
    created: "Sep 20, 2023",
  },
  {
    id: "project30",
    parentId: "projects",

    name: "Product_Photos",
    type: "folder" as const,
    size: { value: 5.2, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Products",
    modified: "Oct 10, 2023",
    created: "Sep 22, 2023",
  },
  {
    id: "project31",
    parentId: "projects",

    name: "User_Research",
    type: "folder" as const,
    size: { value: 1.1, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Research",
    modified: "Oct 12, 2023",
    created: "Sep 25, 2023",
  },
  {
    id: "project32",
    parentId: "projects",

    name: "Brand_Guidelines",
    type: "folder" as const,
    size: { value: 2.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Branding",
    modified: "Oct 15, 2023",
    created: "Sep 28, 2023",
  },
  {
    id: "project33",
    parentId: "projects",

    name: "Illustrations",
    type: "folder" as const,
    size: { value: 3.7, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Art",
    modified: "Oct 18, 2023",
    created: "Oct 01, 2023",
  },
  {
    id: "project34",
    parentId: "projects",

    name: "Prototypes",
    type: "folder" as const,
    size: { value: 1.8, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Development",
    modified: "Oct 20, 2023",
    created: "Oct 05, 2023",
  },
  {
    id: "project35",
    name: "Wireframes",
    type: "folder" as const,
    size: { value: 0.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "UX",
    modified: "Oct 22, 2023",
    created: "Oct 08, 2023",
  },
  {
    id: "project36",
    parentId: "projects",

    name: "Illustrations",
    type: "folder" as const,
    size: { value: 3.7, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Art",
    modified: "Oct 18, 2023",
    created: "Oct 01, 2023",
  },
  {
    id: "project37",
    parentId: "projects",

    name: "Prototypes",
    type: "folder" as const,
    size: { value: 1.8, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Development",
    modified: "Oct 20, 2023",
    created: "Oct 05, 2023",
  },
  {
    id: "project38",
    parentId: "projects",

    name: "Wireframes",
    type: "folder" as const,
    size: { value: 0.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "UX",
    modified: "Oct 22, 2023",
    created: "Oct 08, 2023",
  },
  {
    id: "project39",
    parentId: "projects",

    name: "Video_Edits",
    type: "folder" as const,
    size: { value: 7.4, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Media",
    modified: "Oct 08, 2023",
    created: "Sep 20, 2023",
  },
  {
    id: "project40",
    name: "Product_Photos",
    type: "folder" as const,
    size: { value: 5.2, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Products",
    modified: "Oct 10, 2023",
    created: "Sep 22, 2023",
  },
  {
    id: "project41",
    parentId: "projects",

    name: "User_Research",
    type: "folder" as const,
    size: { value: 1.1, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Research",
    modified: "Oct 12, 2023",
    created: "Sep 25, 2023",
  },
  {
    id: "project42",
    parentId: "projects",

    name: "Brand_Guidelines",
    type: "folder" as const,
    size: { value: 2.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Branding",
    modified: "Oct 15, 2023",
    created: "Sep 28, 2023",
  },
  {
    id: "project43",
    parentId: "projects",

    name: "Illustrations",
    type: "folder" as const,
    size: { value: 3.7, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Art",
    modified: "Oct 18, 2023",
    created: "Oct 01, 2023",
  },
  {
    id: "project44",
    parentId: "projects",

    name: "Prototypes",
    type: "folder" as const,
    size: { value: 1.8, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "Development",
    modified: "Oct 20, 2023",
    created: "Oct 05, 2023",
  },
  {
    id: "project45",
    parentId: "projects",

    name: "Wireframes",
    type: "folder" as const,
    size: { value: 0.9, unit: "GB" as const },
    openIcon: FolderOpen,
    closeIcon: FolderClose,
    owner: "ArtTemplate",
    location: "UX",
    modified: "Oct 22, 2023",
    created: "Oct 08, 2023",
  },
]

// Pagination settings
export const ITEMS_PER_PAGE = 6
